from .._lenient import LenientStrEnum


class BlockExtensionsByPermissionsControlType0BlockedPermissionsItem(LenientStrEnum):
    ACTIVETAB = "activeTab"
    ALARMS = "alarms"
    AUDIOCAPTURE = "audioCapture"
    BACKGROUND = "background"
    BOOKMARKS = "bookmarks"
    BROWSINGDATA = "browsingData"
    CAPTIVEPORTALAUTHENTICATOR = "captivePortalAuthenticator"
    CERTIFICATEPROVIDER = "certificateProvider"
    CLIPBOARDREAD = "clipboardRead"
    CLIPBOARDWRITE = "clipboardWrite"
    CONTENTSETTINGS = "contentSettings"
    CONTEXTMENUS = "contextMenus"
    COOKIES = "cookies"
    CPUMETADATA = "cpuMetadata"
    DEBUGGER = "debugger"
    DECLARATIVECONTENT = "declarativeContent"
    DECLARATIVENETREQUEST = "declarativeNetRequest"
    DESKTOPCAPTURE = "desktopCapture"
    DETECTIDLE = "detectIdle"
    DEVTOOLS = "devtools"
    DISPLAYMETADATA = "displayMetadata"
    DOCUMENTSCAN = "documentScan"
    DOWNLOADS = "downloads"
    DOWNLOADSSHELF = "downloadsShelf"
    ENTERPRISEDEVICEATTRIBUTES = "enterpriseDeviceAttributes"
    EXPERIMENTALAPIS = "experimentalAPIs"
    FILEBROWSERHANDLER = "fileBrowserHandler"
    FILESYSTEM = "fileSystem"
    FILESYSTEMPROVIDER = "fileSystemProvider"
    FONTSETTINGS = "fontSettings"
    FULLSCREENAPPS = "fullscreenApps"
    FULLSCREENOVERRIDEESC = "fullscreenOverrideEsc"
    GCM = "gcm"
    GEOLOCATION = "geolocation"
    HID = "hid"
    HISTORY = "history"
    IDENTITY = "identity"
    IDENTITYEMAIL = "identityEmail"
    LOGINSTATE = "loginState"
    MANAGEMENT = "management"
    MEDIAGALLERIES = "mediaGalleries"
    MEMORYMETADATA = "memoryMetadata"
    NATIVEMESSAGING = "nativeMessaging"
    NETWORKMETADATA = "networkMetadata"
    NOTIFICATIONS = "notifications"
    PAGECAPTURE = "pageCapture"
    PLATFORMKEYS = "platformKeys"
    POWER = "power"
    PRINTERPROVIDER = "printerProvider"
    PRIVACY = "privacy"
    PROCESSES = "processes"
    PROXY = "proxy"
    SCRIPTING = "scripting"
    SEARCH = "search"
    SERIAL = "serial"
    SESSIONS = "sessions"
    SIGNEDINDEVICES = "signedInDevices"
    STORAGE = "storage"
    SYNCFILESYSTEM = "syncFileSystem"
    SYSTEMSTORAGE = "systemStorage"
    TABCAPTURE = "tabCapture"
    TABS = "tabs"
    TOPSITES = "topSites"
    TTSENGINE = "ttsEngine"
    UNLIMITEDSTORAGE = "unlimitedStorage"
    USB = "usb"
    VIDEOCAPTURE = "videoCapture"
    VPNPROVIDER = "vpnProvider"
    WALLPAPER = "wallpaper"
    WEBNAVIGATION = "webNavigation"
    WEBREQUESTS = "webRequests"

    def __str__(self) -> str:
        return str(self.value)
