"""Render the classification table and a cli.yml stub from a CliIR."""

from __future__ import annotations

from .ir import CliIR


def render_table(ir: CliIR, unmapped: list[str]) -> str:
    lines = [f"# {ir.sdk_package} {ir.sdk_version} — {len(ir.commands)} commands"]
    for c in sorted(ir.commands, key=lambda c: (c.verb, c.object, c.variant or "")):
        target = f"{c.verb} {c.object}" + (f" {c.variant}" if c.variant else "")
        lines.append(f"  {target:<40} <- {c.sdk_resource}.{c.sdk_method}")
    if unmapped:
        n = len(unmapped)
        lines.append(f"\n# UNMAPPED ({n}) — map in cli.yml (request:/override:/hide:)")
        for key in sorted(unmapped):
            lines.append(f"  UNMAPPED  {key}")
    return "\n".join(lines)


def render_stub(ir: CliIR, unmapped: list[str]) -> str:
    """A cli.yml stub: TODO entries for unmapped ops. CRUD is auto-classified, so the
    stub only needs the deltas the author must fill in."""
    lines = [
        "# cli.yml stub — generated by `phantasos cli discover`.",
        "# CRUD ops are auto-classified; fill in the non-CRUD ops below.",
        "request:",
    ]
    for key in sorted(unmapped):
        obj = key.split(".")[0].rstrip("s")
        lines.append(f"  # TODO: map {key}")
        lines.append(f"  # {key}: {{object: {obj}, action: CHANGE_ME}}")
    lines.append("hide: []")
    return "\n".join(lines) + "\n"
